//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPMQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChinhSach
    {
        public int ChinhsachID { get; set; }
        public Nullable<int> DieuKienGiao { get; set; }
        public Nullable<int> DoiTraNgay { get; set; }
        public Nullable<int> DoiTraLoiPK { get; set; }
    }
}
