//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPMQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonCT
    {
        public int HoaDonID { get; set; }
        public int KichcoID { get; set; }
        public int MausachID { get; set; }
        public int SanphamID { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SoLuong SoLuong { get; set; }
    }
}
