//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPMQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.HoaDonCTs = new HashSet<HoaDonCT>();
        }
    
        public int HoadonID { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> Tongtien { get; set; }
        public Nullable<int> MaSale { get; set; }
        public Nullable<int> TaiKhoan { get; set; }
        public Nullable<int> Trangthai { get; set; }
    
        public virtual SALE SALE { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonCT> HoaDonCTs { get; set; }
    }
}
