//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPMQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int TaikhoanID { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public System.DateTime Ngaysinh { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string Diachi { get; set; }
        public int Tongchitieu { get; set; }
        public string Matkhau { get; set; }
        public Nullable<int> tichdiemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual TichDiem TichDiem { get; set; }
    }
}
